{{- if and .Values.config.jwt.secretKey (not .Values.config.jwt.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy.fullname" . }}-jwt
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.jwt.existingSecretKey }}: {{ .Values.config.jwt.secretKey | b64enc | quote }}
{{- end }}