{{- if not .Values.global.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbrix.fullname" . }}-postgres
  labels:
    {{- include "qbrix.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.global.postgres.username | b64enc | quote }}
  password: {{ .Values.global.postgres.password | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.global.redis.existingSecret) .Values.global.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbrix.fullname" . }}-redis
  labels:
    {{- include "qbrix.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.global.redis.password | b64enc | quote }}
{{- end }}